### ISSUE TITLE
How can I use addPage() or auto split when I want to export long length data.

### ISSUE THREAD

**Issue by teebeiz** [ivmarcos/react-to-pdf#6]
Here is my options, Can you help me config to solve my problems about split page. thank you so much.
<Pdf targetRef={ref} options={{
                            orientation: 'p',
                            unit: 'mm',
                            format: 'a4',
                            putOnlyUsedFonts: true
                        }} filename="đơn-xin-nghỉ-phép.pdf">
                            {({ toPdf }) => <button onClick={toPdf}>In PDF</button>}</Pdf>

**Comment by stefanorueda** [comment]
> Here is my options, Can you help me config to solve my problems about split page. thank you so much.
> <Pdf targetRef={ref} options={{
> orientation: 'p',
> unit: 'mm',
> format: 'a4',
> putOnlyUsedFonts: true
> }} filename="đơn-xin-nghỉ-phép.pdf">
> {({ toPdf }) => In PDF}

I also need the answer to this issue

**Comment by ivmarcos** [comment]
As mentioned in README, it only supports single page. The multi-page feature is not currently being planned because the final file may be overly large, due to conversion to canvas in process. In this case I would suggest using https://react-pdf.org/ or use both html2canvas and jsPdf to manipulate the result as you want, e.g. http://jsfiddle.net/rpaul/p4s5k59s/5/
